[tool.poetry]
name = "Poke"
version = "0.1.0"
description = ""
authors = ["Ian <Ian.allheim@gmail.com.com>"]

[tool.poetry.dependencies]
hmac_auth = { version = "^0.1", source = "datto" }
python = "^3.9"
playwright = "^1.17.2"
pytest-xdist = "^1.34"
hvac = "^0.11.2"
pytest = "^6.2"
pytest-flakefinder = "^1.0.0"
tomli = "^2.0.1"
randomname = "^0.1.5"
pyotp = "^2.6.0"
tomli-w = "^1.0.0"
click = "^8.1.3"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

